version: '3.9'

services:

  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: appointment_db  # Database name for the project
      POSTGRES_USER: appointment_user  # Username for the project
      POSTGRES_PASSWORD: secure_password  # Replace with a secure password
    volumes:
      - postgresql-data:/var/lib/postgresql/data  # Persist database data

volumes:
  postgresql-data:
    driver: local